using EventEase.Domain.Common;
using EventEase.Domain.Enums;

namespace EventEase.Domain.Entities;

/// <summary>
/// Represents an invitation sent to a guest for an event
/// </summary>
public class Invitation : BaseAuditableEntity, ITenantEntity
{
    public Guid TenantId { get; set; }
    public Guid EventId { get; set; }
    public Guid GuestId { get; set; }
    public Guid SentByUserId { get; set; }

    // Status
    public InvitationStatus Status { get; set; } = InvitationStatus.Draft;

    // Content
    public string Subject { get; set; } = string.Empty;
    public string? MessageBody { get; set; }
    public bool IsAIGenerated { get; set; } = false;
    public Guid? AIAgentUsageId { get; set; } // If generated by Invitation Agent

    // Scheduling
    public DateTime? ScheduledSendAt { get; set; } // AI-optimized send time
    public DateTime? SentAt { get; set; }

    // Tracking
    public DateTime? OpenedAt { get; set; }
    public DateTime? ClickedAt { get; set; }
    public DateTime? RespondedAt { get; set; }
    public int OpenCount { get; set; } = 0;
    public int ClickCount { get; set; } = 0;

    // Unique Token for tracking
    public string TrackingToken { get; set; } = Guid.NewGuid().ToString();

    // Email Provider Details
    public string? SendGridMessageId { get; set; }
    public string? SendGridStatus { get; set; }
    public string? ErrorMessage { get; set; }

    // Metadata
    public string? Metadata { get; set; } // JSON object

    // Navigation Properties
    public virtual Tenant Tenant { get; set; } = null!;
    public virtual Event Event { get; set; } = null!;
    public virtual Guest Guest { get; set; } = null!;
    public virtual User SentByUser { get; set; } = null!;
    public virtual AIAgentUsage? AIAgentUsage { get; set; }
    public virtual EventRegistration? Registration { get; set; } // If invitation led to registration
}
